### ISSUE TITLE
Handle JWT Auth

### ISSUE THREAD

**Issue by Brich96** [Brich96/usu-gdsf#16]

**Comment by ted-tanner** [comment]
This is handled by merges 654fb59 and ac7406c. Token refresh will be handled as part of issue #15 because @jdasnake81 wanted to take a greater role in writing the routes for authentication.

A JSON Web Token (JWT) is specific thing and the tokens I implemented do not follow the JWT standard. That is on purpose. JWT implementations have been fraught with security issues in the past and often libraries need intense vetting before they can be used. See [here](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/) and [here](https://medium.com/swlh/hacking-json-web-tokens-jwts-9122efe91e4a). My implementation discards nearly all the troublesome flaws and configuration issues but keeps the root that makes JWTs secure in principle. These tokens use the same cryptograph hash function (SHA 256 HMAC) to generate the signature. The "security essence" of JWTs is maintained without any of the customization which can make implementations problematic.
